#
# Defines an elastic sink for reporting metrics to an ElasticSearch instance
# Settings:
#   type                                  - sink type (must be elastic for ElasticSearch support)
#   name                                  - name for the sink instance
#   settings.host                         - ElasticSearch host settings
#   settings.host.protocol                - protocol to use, http or https (default)
#   settings.host.domain                  - host domain
#   settings.host.certificateFilePath     - path to certificate file (optional)
#   settings.host.port                    - port number (default 9200)
#   settings.host.authentication          - authentication settings if authentication is enabled (optional)
#   settings.host.authentication.type     - authentication type (determines remaining settings) (only 'basic' is supported)
#   settings.host.authentication.username - username for basic authentication (if not stored in a secret)
#   settings.host.authentication.password - encrypted password for basic authentication (if not stored in a secret)
#   settings.host.authentication.credentialsSecret  - name of secret containing username and password for basic authentication
#   settings.host.authentication.credentialsVaultId - optional vault id for secret containing username password for basic authentication
#   settings.index                        - ElasticSearch index settings
#   settings.index.name                   - index name
#   settings.index.countSuffixMappingName    - dynamic template mapping object name for count metrics suffixes (default: hpcc_metrics_count_suffix)
#   settings.index.gaugeSuffixMappingName    - dynamic template mapping object name for gauge metrics suffixes (default: hpcc_metrics_gauge_suffix)
#   settings.index.histogramSuffixMappingName - dynamic template mapping object name for histogram metrics suffixes (default: hpcc_metrics_histogram_suffix)
#
# If not overridden, the following suffixes are used by default:
#   countMetricSuffix: count
#   gaugeMetricSuffix: gauge
#   histogramMetricSuffix: histogram

global:
  metrics:
    sinks:
    - type: elastic
      name: myelasticsink
      settings:
        host:
          protocol: https
          domain: domain
          port: 9200
          certificateFilePath: "path/to/cert"
          authentication:
            type: basic
            username: username
            password: password
            credentialsSecret: secretName
            credentialsVaultId: vaultId
        index:
          name: hpccmetrics
          countSuffixMappingName: name
          gaugeSuffixMappingName: name
          histogramSuffixMappingName: name