#
# Defines an elastic sink for reporting metrics to an ElasticSearch instance
# Settings:
#   type                                - sink type (must be elastic for ElasticSearch support)
#   name                                - name for the sink instance
#   settings.countMetricSuffix          - suffix for count metrics (default: count)
#   settings.gaugeMetricSuffix          - suffix for gauge metrics (default: gauge)
#   settings.histogramMetricSuffix      - suffix for histogram metrics (default: histogram)
#   settings.host                       - ElasticSearch host settings
#   settings.host.protocol               - protocol to use, http or https (default)
#   settings.host.name                   - host name
#   settings.host.port                   - port number (default 9200)
#   settings.index                       - ElasticSearch index settings
#   settings.index.name                  - index name
#
# If not overridden, the following suffixes are used by default:
#   countMetricSuffix: count
#   gaugeMetricSuffix: gauge
#   histogramMetricSuffix: histogram

global:
  metrics:
    sinks:
    - type: elastic
      name: myelasticsink
      settings:
        countMetricSuffix: count
        gaugeMetricSuffix: gauge
        histogramMetricSuffix: histogram
        host:
          protocol: https
          name: hostname
          port: 9200
        index:
          name: hpccmetrics

